In [26]:
import pandas as pd
import os
def process_files_in_directory(directory_path):
    # Initialize an empty dictionary to store data
    data = {}

    # Loop through each file in the directory
    for filename in os.listdir(directory_path):
        # Only process .txt files
        if filename.endswith('.txt'):
            file_path = os.path.join(directory_path, filename)
            column_name = filename  # Use the filename as the column name
            
            with open(file_path, 'r') as file:
                file_data = {}
                for line in file:
                    # Split line into file entry name and its value
                    entry_name, value = line.strip().split()
                    try:
                        file_data[entry_name] = int(value)
                    except ValueError:
                        file_data[entry_name] = value
            
            # Add this file's data to the main data dictionary under its filename
            data[column_name] = file_data

    # Convert the dictionary of dictionaries to a DataFrame
    df = pd.DataFrame(data).sort_index()

    return df

# Usage example
directory_path = 'results'
df = process_files_in_directory(directory_path)

In [27]:
# column map
column_map = {
    'n.txt': 'n',
    'alternate.txt': 'A',
    'few.txt': 'F',
    'many.txt': 'M',
    'none.txt': 'N',
    'some.txt': 'S',
}
df = df.rename(columns=column_map)
df = df[['n','A', 'F', 'M', 'N', 'S']]
df  = df.reset_index()
df = df[df['n'] >= 500]

In [28]:
df["index"] = df["index"].str.replace('.txt', '')
df['M'] = df['M'].replace('Undirected', '?!')
df['S'] = df['S'].replace('True', 'true')
df['S'] = df['S'].replace('False', 'false')
df['S'] = df['S'].replace('Timeout_3600_s', 'TO')
df['S'] = df['S'].replace('UnknownError', 'ME')

In [29]:
df

             index      n      A  F   M  N      S
2              bht   5757  false  0  ?!  6     TO
4    common-1-1000   1000  false -1  ?! -1  false
5    common-1-1500   1500  false -1  ?! -1  false
7    common-1-2000   2000  false -1  ?! -1  false
9    common-1-2500   2500  false  1  ?!  6   true
..             ...    ...    ... ..  .. ..    ...
142    wall-p-1000   6002  false  0  ?!  1   true
143   wall-p-10000  60002  false  0  ?!  1     ME
149     wall-z-100    701  false  0  ?!  1   true
150    wall-z-1000   7001  false  0  ?!  1   true
151   wall-z-10000  70001  false  0  ?!  1     ME

[83 rows x 7 columns]

In [30]:
import pandas as pd

# Define a function to convert a pandas DataFrame to a LaTeX table
def dataframe_to_latex(df):
    # Generate the LaTeX table structure
    latex_table = r"""
\medskip
\begin{tabular}{lrrrrrrr}
  \toprule
  Instance name & n & A & F & M & N & S \\
  \midrule
"""
    # Populate the rows from the DataFrame
    for _, row in df.iterrows():
        latex_table += f"  {row['index']} & {row['n']} & {row['A']} & {row['F']} & {row['M']} & {row['N']} & {row['S']} \\\\\n"
    
    latex_table += r"""  \bottomrule
\end{tabular}
\medskip
"""
    return latex_table

# Convert the DataFrame to LaTeX table
latex_code = dataframe_to_latex(df)

# Display the LaTeX code
print(latex_code)

\medskip
\begin{tabular}{lrrrrrrr}
  \toprule
  Instance name & n & A & F & M & N & S \\
  \midrule
  bht & 5757 & false & 0 & ?! & 6 & TO \\
  common-1-1000 & 1000 & false & -1 & ?! & -1 & false \\
  common-1-1500 & 1500 & false & -1 & ?! & -1 & false \\
  common-1-2000 & 2000 & false & -1 & ?! & -1 & false \\
  common-1-2500 & 2500 & false & 1 & ?! & 6 & true \\
  common-1-3000 & 3000 & false & 1 & ?! & 6 & true \\
  common-1-3500 & 3500 & false & 1 & ?! & 6 & TO \\
  common-1-4000 & 4000 & false & 1 & ?! & 6 & TO \\
  common-1-4500 & 4500 & true & 1 & ?! & 6 & TO \\
  common-1-500 & 500 & false & -1 & ?! & -1 & false \\
  common-1-5000 & 5000 & true & 1 & ?! & 6 & true \\
  common-1-5757 & 5757 & true & 1 & ?! & 6 & true \\
  common-2-1000 & 1000 & true & 1 & ?! & 4 & true \\
  common-2-1500 & 1500 & true & 1 & ?! & 4 & true \\
  common-2-2000 & 2000 & true & 1 & ?! & 4 & true \\
  common-2-2500 & 2500 & true & 1 & ?! & 4 & true \\
  common-2-3000 & 3000 & true & 1 & ?! & 4 & true \\
  common-2-3500 & 3500 & true & 1 & ?! & 4 & true \\
  common-2-4000 & 4000 & true & 1 & ?! & 4 & true \\
  common-2-4500 & 4500 & true & 1 & ?! & 4 & true \\
  common-2-500 & 500 & true & 1 & ?! & 4 & true \\
  common-2-5000 & 5000 & true & 1 & ?! & 4 & true \\
  common-2-5757 & 5757 & true & 1 & ?! & 4 & true \\
  gnm-1000-1500-0 & 1000 & false & 1 & ?! & -1 & true \\
  gnm-1000-1500-1 & 1000 & false & 2 & ?! & -1 & true \\
  gnm-1000-2000-0 & 1000 & false & 0 & ?! & 7 & true \\
  gnm-1000-2000-1 & 1000 & false & 2 & ?! & -1 & true \\
  gnm-2000-3000-0 & 2000 & false & 0 & ?! & 8 & true \\
  gnm-2000-3000-1 & 2000 & true & 2 & ?! & -1 & true \\
  gnm-2000-4000-0 & 2000 & false & 0 & ?! & 6 & true \\
  gnm-2000-4000-1 & 2000 & false & 0 & ?! & 5 & true \\
  gnm-3000-4500-0 & 3000 & false & 0 & ?! & 10 & true \\
  gnm-3000-4500-1 & 3000 & false & 2 & ?! & -1 & true \\
  gnm-3000-6000-0 & 3000 & false & 0 & ?! & 6 & true \\
  gnm-3000-6000-1 & 3000 & false & 2 & ?! & 6 & true \\
  gnm-4000-6000-0 & 4000 & false & 0 & ?! & 7 & true \\
  gnm-4000-6000-1 & 4000 & false & 1 & ?! & 15 & true \\
  gnm-4000-8000-0 & 4000 & false & 0 & ?! & 5 & true \\
  gnm-4000-8000-1 & 4000 & true & 2 & ?! & 6 & true \\
  gnm-5000-10000-0 & 5000 & false & 2 & ?! & 5 & true \\
  gnm-5000-10000-1 & 5000 & true & 1 & ?! & 5 & true \\
  gnm-5000-7500-0 & 5000 & false & -1 & ?! & -1 & TO \\
  gnm-5000-7500-1 & 5000 & false & -1 & ?! & -1 & TO \\
  grid-25-0 & 625 & true & 0 & ?! & 324 & true \\
  grid-25-1 & 625 & true & 0 & ?! & 123 & true \\
  grid-25-2 & 625 & true & 5 & ?! & -1 & true \\
  grid-50-0 & 2500 & false & 0 & ?! & 1249 & true \\
  grid-50-1 & 2500 & false & 0 & ?! & 521 & true \\
  grid-50-2 & 2500 & false & 11 & ?! & -1 & true \\
  increase-n500-1 & 500 & true & 2 & 15 & 1 & true \\
  increase-n500-2 & 500 & true & 1 & 17 & 1 & true \\
  increase-n500-3 & 500 & true & 1 & 16 & 1 & true \\
  rusty-1-2000 & 2000 & false & -1 & ?! & -1 & false \\
  rusty-1-2500 & 2500 & false & -1 & ?! & -1 & TO \\
  rusty-1-3000 & 3000 & false & 0 & ?! & 14 & true \\
  rusty-1-3500 & 3500 & false & 0 & ?! & 14 & true \\
  rusty-1-4000 & 4000 & false & 0 & ?! & 13 & true \\
  rusty-1-4500 & 4500 & false & 0 & ?! & 7 & true \\
  rusty-1-5000 & 5000 & false & 0 & ?! & 7 & true \\
  rusty-1-5757 & 5757 & false & 0 & ?! & 7 & TO \\
  rusty-2-2000 & 2000 & false & 0 & ?! & 5 & true \\
  rusty-2-2500 & 2500 & false & 0 & ?! & 4 & true \\
  rusty-2-3000 & 3000 & false & 0 & ?! & 4 & true \\
  rusty-2-3500 & 3500 & false & 0 & ?! & 4 & true \\
  rusty-2-4000 & 4000 & false & 0 & ?! & 4 & true \\
  rusty-2-4500 & 4500 & false & 0 & ?! & 4 & true \\
  rusty-2-5000 & 5000 & false & 0 & ?! & 4 & true \\
  rusty-2-5757 & 5757 & false & 0 & ?! & 4 & TO \\
  smallworld-30-0 & 900 & false & 0 & ?! & 9 & true \\
  smallworld-30-1 & 900 & true & 1 & ?! & 11 & true \\
  smallworld-40-0 & 1600 & false & 0 & ?! & 8 & true \\
  smallworld-40-1 & 1600 & true & 1 & ?! & 13 & true \\
  smallworld-50-0 & 2500 & false & 0 & ?! & 3 & true \\
  smallworld-50-1 & 2500 & true & 2 & ?! & -1 & true \\
  wall-n-100 & 800 & false & 0 & ?! & 1 & true \\
  wall-n-1000 & 8000 & false & 0 & ?! & 1 & true \\
  wall-n-10000 & 80000 & false & 0 & ?! & 1 & ME \\
  wall-p-100 & 602 & false & 0 & ?! & 1 & true \\
  wall-p-1000 & 6002 & false & 0 & ?! & 1 & true \\
  wall-p-10000 & 60002 & false & 0 & ?! & 1 & ME \\
  wall-z-100 & 701 & false & 0 & ?! & 1 & true \\
  wall-z-1000 & 7001 & false & 0 & ?! & 1 & true \\
  wall-z-10000 & 70001 & false & 0 & ?! & 1 & ME \\
  \bottomrule
\end{tabular}
\medskip

In [31]:
output_file = "results.txt"
df.to_csv(output_file, sep='\t', index=False)